// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.space_api.proto;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes document = 1;</code>
   */
  com.google.protobuf.ByteString getDocument();

  /**
   * <code>string operation = 2;</code>
   */
  java.lang.String getOperation();
  /**
   * <code>string operation = 2;</code>
   */
  com.google.protobuf.ByteString
      getOperationBytes();

  /**
   * <code>.proto.Meta meta = 3;</code>
   */
  boolean hasMeta();
  /**
   * <code>.proto.Meta meta = 3;</code>
   */
  com.spaceuptech.space_api.proto.Meta getMeta();
  /**
   * <code>.proto.Meta meta = 3;</code>
   */
  com.spaceuptech.space_api.proto.MetaOrBuilder getMetaOrBuilder();
}
