// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.space_api.proto;

public interface FunctionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.FunctionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes params = 1;</code>
   */
  com.google.protobuf.ByteString getParams();

  /**
   * <code>int64 timeout = 2;</code>
   */
  long getTimeout();

  /**
   * <code>string service = 3;</code>
   */
  java.lang.String getService();
  /**
   * <code>string service = 3;</code>
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>string function = 4;</code>
   */
  java.lang.String getFunction();
  /**
   * <code>string function = 4;</code>
   */
  com.google.protobuf.ByteString
      getFunctionBytes();

  /**
   * <code>string token = 5;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 5;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string project = 6;</code>
   */
  java.lang.String getProject();
  /**
   * <code>string project = 6;</code>
   */
  com.google.protobuf.ByteString
      getProjectBytes();
}
