// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.space_api.proto;

public interface FunctionsPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.FunctionsPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes auth = 1;</code>
   */
  com.google.protobuf.ByteString getAuth();

  /**
   * <code>bytes params = 2;</code>
   */
  com.google.protobuf.ByteString getParams();

  /**
   * <code>string service = 3;</code>
   */
  java.lang.String getService();
  /**
   * <code>string service = 3;</code>
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>string function = 4;</code>
   */
  java.lang.String getFunction();
  /**
   * <code>string function = 4;</code>
   */
  com.google.protobuf.ByteString
      getFunctionBytes();

  /**
   * <code>string type = 5;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 5;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string id = 6;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 6;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string error = 7;</code>
   */
  java.lang.String getError();
  /**
   * <code>string error = 7;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>string project = 8;</code>
   */
  java.lang.String getProject();
  /**
   * <code>string project = 8;</code>
   */
  com.google.protobuf.ByteString
      getProjectBytes();

  /**
   * <code>string token = 9;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 9;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
