// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.space_api.proto;

public interface MetaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Meta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string project = 1;</code>
   */
  java.lang.String getProject();
  /**
   * <code>string project = 1;</code>
   */
  com.google.protobuf.ByteString
      getProjectBytes();

  /**
   * <code>string dbType = 2;</code>
   */
  java.lang.String getDbType();
  /**
   * <code>string dbType = 2;</code>
   */
  com.google.protobuf.ByteString
      getDbTypeBytes();

  /**
   * <code>string col = 3;</code>
   */
  java.lang.String getCol();
  /**
   * <code>string col = 3;</code>
   */
  com.google.protobuf.ByteString
      getColBytes();

  /**
   * <code>string token = 4;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 4;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
