// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.space_api.proto;

public interface PubsubSubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PubsubSubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string subject = 1;</code>
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 1;</code>
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string queue = 2;</code>
   */
  java.lang.String getQueue();
  /**
   * <code>string queue = 2;</code>
   */
  com.google.protobuf.ByteString
      getQueueBytes();

  /**
   * <code>string type = 3;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string token = 4;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 4;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string project = 5;</code>
   */
  java.lang.String getProject();
  /**
   * <code>string project = 5;</code>
   */
  com.google.protobuf.ByteString
      getProjectBytes();

  /**
   * <code>string id = 6;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 6;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
