// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.space_api.proto;

public interface PubsubMsgResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PubsubMsgResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>int32 status = 3;</code>
   */
  int getStatus();

  /**
   * <code>string error = 4;</code>
   */
  java.lang.String getError();
  /**
   * <code>string error = 4;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>bytes msg = 5;</code>
   */
  com.google.protobuf.ByteString getMsg();
}
