// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.space_api.proto;

/**
 * Protobuf type {@code proto.ReadOptions}
 */
public  final class ReadOptions extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.ReadOptions)
    ReadOptionsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReadOptions.newBuilder() to construct.
  private ReadOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReadOptions() {
    distinct_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReadOptions(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              select_ = com.google.protobuf.MapField.newMapField(
                  SelectDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
            select__ = input.readMessage(
                SelectDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            select_.getMutableMap().put(
                select__.getKey(), select__.getValue());
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              sort_ = com.google.protobuf.MapField.newMapField(
                  SortDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
            sort__ = input.readMessage(
                SortDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            sort_.getMutableMap().put(
                sort__.getKey(), sort__.getValue());
            break;
          }
          case 24: {

            skip_ = input.readInt64();
            break;
          }
          case 32: {

            limit_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            distinct_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.spaceuptech.space_api.proto.SpaceCloudProto.internal_static_proto_ReadOptions_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetSelect();
      case 2:
        return internalGetSort();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.spaceuptech.space_api.proto.SpaceCloudProto.internal_static_proto_ReadOptions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.spaceuptech.space_api.proto.ReadOptions.class, com.spaceuptech.space_api.proto.ReadOptions.Builder.class);
  }

  private int bitField0_;
  public static final int SELECT_FIELD_NUMBER = 1;
  private static final class SelectDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Integer>newDefaultInstance(
                com.spaceuptech.space_api.proto.SpaceCloudProto.internal_static_proto_ReadOptions_SelectEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Integer> select_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
  internalGetSelect() {
    if (select_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SelectDefaultEntryHolder.defaultEntry);
    }
    return select_;
  }

  public int getSelectCount() {
    return internalGetSelect().getMap().size();
  }
  /**
   * <code>map&lt;string, int32&gt; select = 1;</code>
   */

  public boolean containsSelect(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetSelect().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSelectMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Integer> getSelect() {
    return getSelectMap();
  }
  /**
   * <code>map&lt;string, int32&gt; select = 1;</code>
   */

  public java.util.Map<java.lang.String, java.lang.Integer> getSelectMap() {
    return internalGetSelect().getMap();
  }
  /**
   * <code>map&lt;string, int32&gt; select = 1;</code>
   */

  public int getSelectOrDefault(
      java.lang.String key,
      int defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetSelect().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, int32&gt; select = 1;</code>
   */

  public int getSelectOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetSelect().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int SORT_FIELD_NUMBER = 2;
  private static final class SortDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Integer>newDefaultInstance(
                com.spaceuptech.space_api.proto.SpaceCloudProto.internal_static_proto_ReadOptions_SortEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Integer> sort_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
  internalGetSort() {
    if (sort_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SortDefaultEntryHolder.defaultEntry);
    }
    return sort_;
  }

  public int getSortCount() {
    return internalGetSort().getMap().size();
  }
  /**
   * <code>map&lt;string, int32&gt; sort = 2;</code>
   */

  public boolean containsSort(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetSort().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSortMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Integer> getSort() {
    return getSortMap();
  }
  /**
   * <code>map&lt;string, int32&gt; sort = 2;</code>
   */

  public java.util.Map<java.lang.String, java.lang.Integer> getSortMap() {
    return internalGetSort().getMap();
  }
  /**
   * <code>map&lt;string, int32&gt; sort = 2;</code>
   */

  public int getSortOrDefault(
      java.lang.String key,
      int defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetSort().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, int32&gt; sort = 2;</code>
   */

  public int getSortOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetSort().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int SKIP_FIELD_NUMBER = 3;
  private long skip_;
  /**
   * <code>int64 skip = 3;</code>
   */
  public long getSkip() {
    return skip_;
  }

  public static final int LIMIT_FIELD_NUMBER = 4;
  private long limit_;
  /**
   * <code>int64 limit = 4;</code>
   */
  public long getLimit() {
    return limit_;
  }

  public static final int DISTINCT_FIELD_NUMBER = 5;
  private volatile java.lang.Object distinct_;
  /**
   * <code>string distinct = 5;</code>
   */
  public java.lang.String getDistinct() {
    java.lang.Object ref = distinct_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      distinct_ = s;
      return s;
    }
  }
  /**
   * <code>string distinct = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDistinctBytes() {
    java.lang.Object ref = distinct_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      distinct_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetSelect(),
        SelectDefaultEntryHolder.defaultEntry,
        1);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetSort(),
        SortDefaultEntryHolder.defaultEntry,
        2);
    if (skip_ != 0L) {
      output.writeInt64(3, skip_);
    }
    if (limit_ != 0L) {
      output.writeInt64(4, limit_);
    }
    if (!getDistinctBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, distinct_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
         : internalGetSelect().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
      select__ = SelectDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, select__);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
         : internalGetSort().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
      sort__ = SortDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, sort__);
    }
    if (skip_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, skip_);
    }
    if (limit_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, limit_);
    }
    if (!getDistinctBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, distinct_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.spaceuptech.space_api.proto.ReadOptions)) {
      return super.equals(obj);
    }
    com.spaceuptech.space_api.proto.ReadOptions other = (com.spaceuptech.space_api.proto.ReadOptions) obj;

    if (!internalGetSelect().equals(
        other.internalGetSelect())) return false;
    if (!internalGetSort().equals(
        other.internalGetSort())) return false;
    if (getSkip()
        != other.getSkip()) return false;
    if (getLimit()
        != other.getLimit()) return false;
    if (!getDistinct()
        .equals(other.getDistinct())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetSelect().getMap().isEmpty()) {
      hash = (37 * hash) + SELECT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSelect().hashCode();
    }
    if (!internalGetSort().getMap().isEmpty()) {
      hash = (37 * hash) + SORT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSort().hashCode();
    }
    hash = (37 * hash) + SKIP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSkip());
    hash = (37 * hash) + LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLimit());
    hash = (37 * hash) + DISTINCT_FIELD_NUMBER;
    hash = (53 * hash) + getDistinct().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.spaceuptech.space_api.proto.ReadOptions parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spaceuptech.space_api.proto.ReadOptions parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spaceuptech.space_api.proto.ReadOptions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spaceuptech.space_api.proto.ReadOptions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spaceuptech.space_api.proto.ReadOptions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spaceuptech.space_api.proto.ReadOptions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spaceuptech.space_api.proto.ReadOptions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.spaceuptech.space_api.proto.ReadOptions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.spaceuptech.space_api.proto.ReadOptions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.spaceuptech.space_api.proto.ReadOptions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.spaceuptech.space_api.proto.ReadOptions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.spaceuptech.space_api.proto.ReadOptions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.spaceuptech.space_api.proto.ReadOptions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.ReadOptions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.ReadOptions)
      com.spaceuptech.space_api.proto.ReadOptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spaceuptech.space_api.proto.SpaceCloudProto.internal_static_proto_ReadOptions_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetSelect();
        case 2:
          return internalGetSort();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableSelect();
        case 2:
          return internalGetMutableSort();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spaceuptech.space_api.proto.SpaceCloudProto.internal_static_proto_ReadOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.spaceuptech.space_api.proto.ReadOptions.class, com.spaceuptech.space_api.proto.ReadOptions.Builder.class);
    }

    // Construct using com.spaceuptech.space_api.proto.ReadOptions.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableSelect().clear();
      internalGetMutableSort().clear();
      skip_ = 0L;

      limit_ = 0L;

      distinct_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.spaceuptech.space_api.proto.SpaceCloudProto.internal_static_proto_ReadOptions_descriptor;
    }

    @java.lang.Override
    public com.spaceuptech.space_api.proto.ReadOptions getDefaultInstanceForType() {
      return com.spaceuptech.space_api.proto.ReadOptions.getDefaultInstance();
    }

    @java.lang.Override
    public com.spaceuptech.space_api.proto.ReadOptions build() {
      com.spaceuptech.space_api.proto.ReadOptions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.spaceuptech.space_api.proto.ReadOptions buildPartial() {
      com.spaceuptech.space_api.proto.ReadOptions result = new com.spaceuptech.space_api.proto.ReadOptions(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.select_ = internalGetSelect();
      result.select_.makeImmutable();
      result.sort_ = internalGetSort();
      result.sort_.makeImmutable();
      result.skip_ = skip_;
      result.limit_ = limit_;
      result.distinct_ = distinct_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.spaceuptech.space_api.proto.ReadOptions) {
        return mergeFrom((com.spaceuptech.space_api.proto.ReadOptions)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.spaceuptech.space_api.proto.ReadOptions other) {
      if (other == com.spaceuptech.space_api.proto.ReadOptions.getDefaultInstance()) return this;
      internalGetMutableSelect().mergeFrom(
          other.internalGetSelect());
      internalGetMutableSort().mergeFrom(
          other.internalGetSort());
      if (other.getSkip() != 0L) {
        setSkip(other.getSkip());
      }
      if (other.getLimit() != 0L) {
        setLimit(other.getLimit());
      }
      if (!other.getDistinct().isEmpty()) {
        distinct_ = other.distinct_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.spaceuptech.space_api.proto.ReadOptions parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.spaceuptech.space_api.proto.ReadOptions) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> select_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetSelect() {
      if (select_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SelectDefaultEntryHolder.defaultEntry);
      }
      return select_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetMutableSelect() {
      onChanged();;
      if (select_ == null) {
        select_ = com.google.protobuf.MapField.newMapField(
            SelectDefaultEntryHolder.defaultEntry);
      }
      if (!select_.isMutable()) {
        select_ = select_.copy();
      }
      return select_;
    }

    public int getSelectCount() {
      return internalGetSelect().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; select = 1;</code>
     */

    public boolean containsSelect(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetSelect().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSelectMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getSelect() {
      return getSelectMap();
    }
    /**
     * <code>map&lt;string, int32&gt; select = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Integer> getSelectMap() {
      return internalGetSelect().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; select = 1;</code>
     */

    public int getSelectOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetSelect().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; select = 1;</code>
     */

    public int getSelectOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetSelect().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearSelect() {
      internalGetMutableSelect().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, int32&gt; select = 1;</code>
     */

    public Builder removeSelect(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableSelect().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer>
    getMutableSelect() {
      return internalGetMutableSelect().getMutableMap();
    }
    /**
     * <code>map&lt;string, int32&gt; select = 1;</code>
     */
    public Builder putSelect(
        java.lang.String key,
        int value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      
      internalGetMutableSelect().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, int32&gt; select = 1;</code>
     */

    public Builder putAllSelect(
        java.util.Map<java.lang.String, java.lang.Integer> values) {
      internalGetMutableSelect().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> sort_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetSort() {
      if (sort_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SortDefaultEntryHolder.defaultEntry);
      }
      return sort_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetMutableSort() {
      onChanged();;
      if (sort_ == null) {
        sort_ = com.google.protobuf.MapField.newMapField(
            SortDefaultEntryHolder.defaultEntry);
      }
      if (!sort_.isMutable()) {
        sort_ = sort_.copy();
      }
      return sort_;
    }

    public int getSortCount() {
      return internalGetSort().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; sort = 2;</code>
     */

    public boolean containsSort(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetSort().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSortMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getSort() {
      return getSortMap();
    }
    /**
     * <code>map&lt;string, int32&gt; sort = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Integer> getSortMap() {
      return internalGetSort().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; sort = 2;</code>
     */

    public int getSortOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetSort().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; sort = 2;</code>
     */

    public int getSortOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetSort().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearSort() {
      internalGetMutableSort().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, int32&gt; sort = 2;</code>
     */

    public Builder removeSort(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableSort().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer>
    getMutableSort() {
      return internalGetMutableSort().getMutableMap();
    }
    /**
     * <code>map&lt;string, int32&gt; sort = 2;</code>
     */
    public Builder putSort(
        java.lang.String key,
        int value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      
      internalGetMutableSort().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, int32&gt; sort = 2;</code>
     */

    public Builder putAllSort(
        java.util.Map<java.lang.String, java.lang.Integer> values) {
      internalGetMutableSort().getMutableMap()
          .putAll(values);
      return this;
    }

    private long skip_ ;
    /**
     * <code>int64 skip = 3;</code>
     */
    public long getSkip() {
      return skip_;
    }
    /**
     * <code>int64 skip = 3;</code>
     */
    public Builder setSkip(long value) {
      
      skip_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 skip = 3;</code>
     */
    public Builder clearSkip() {
      
      skip_ = 0L;
      onChanged();
      return this;
    }

    private long limit_ ;
    /**
     * <code>int64 limit = 4;</code>
     */
    public long getLimit() {
      return limit_;
    }
    /**
     * <code>int64 limit = 4;</code>
     */
    public Builder setLimit(long value) {
      
      limit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 limit = 4;</code>
     */
    public Builder clearLimit() {
      
      limit_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object distinct_ = "";
    /**
     * <code>string distinct = 5;</code>
     */
    public java.lang.String getDistinct() {
      java.lang.Object ref = distinct_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        distinct_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string distinct = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDistinctBytes() {
      java.lang.Object ref = distinct_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        distinct_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string distinct = 5;</code>
     */
    public Builder setDistinct(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      distinct_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string distinct = 5;</code>
     */
    public Builder clearDistinct() {
      
      distinct_ = getDefaultInstance().getDistinct();
      onChanged();
      return this;
    }
    /**
     * <code>string distinct = 5;</code>
     */
    public Builder setDistinctBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      distinct_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.ReadOptions)
  }

  // @@protoc_insertion_point(class_scope:proto.ReadOptions)
  private static final com.spaceuptech.space_api.proto.ReadOptions DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.spaceuptech.space_api.proto.ReadOptions();
  }

  public static com.spaceuptech.space_api.proto.ReadOptions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReadOptions>
      PARSER = new com.google.protobuf.AbstractParser<ReadOptions>() {
    @java.lang.Override
    public ReadOptions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReadOptions(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReadOptions> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReadOptions> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.spaceuptech.space_api.proto.ReadOptions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

