// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.space_api.proto;

public interface ReadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ReadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes find = 1;</code>
   */
  com.google.protobuf.ByteString getFind();

  /**
   * <code>string operation = 2;</code>
   */
  java.lang.String getOperation();
  /**
   * <code>string operation = 2;</code>
   */
  com.google.protobuf.ByteString
      getOperationBytes();

  /**
   * <code>.proto.ReadOptions options = 3;</code>
   */
  boolean hasOptions();
  /**
   * <code>.proto.ReadOptions options = 3;</code>
   */
  com.spaceuptech.space_api.proto.ReadOptions getOptions();
  /**
   * <code>.proto.ReadOptions options = 3;</code>
   */
  com.spaceuptech.space_api.proto.ReadOptionsOrBuilder getOptionsOrBuilder();

  /**
   * <code>.proto.Meta meta = 4;</code>
   */
  boolean hasMeta();
  /**
   * <code>.proto.Meta meta = 4;</code>
   */
  com.spaceuptech.space_api.proto.Meta getMeta();
  /**
   * <code>.proto.Meta meta = 4;</code>
   */
  com.spaceuptech.space_api.proto.MetaOrBuilder getMetaOrBuilder();
}
