// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.space_api.proto;

public interface RealTimeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.RealTimeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string dbType = 2;</code>
   */
  java.lang.String getDbType();
  /**
   * <code>string dbType = 2;</code>
   */
  com.google.protobuf.ByteString
      getDbTypeBytes();

  /**
   * <code>string project = 3;</code>
   */
  java.lang.String getProject();
  /**
   * <code>string project = 3;</code>
   */
  com.google.protobuf.ByteString
      getProjectBytes();

  /**
   * <code>string group = 4;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 4;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string type = 5;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 5;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string id = 6;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 6;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>bytes where = 7;</code>
   */
  com.google.protobuf.ByteString getWhere();

  /**
   * <code>bytes options = 8;</code>
   */
  com.google.protobuf.ByteString getOptions();
}
