// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.space_api.proto;

public final class SpaceCloudProto {
  private SpaceCloudProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReadOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ReadOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReadOptions_SelectEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ReadOptions_SelectEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReadOptions_SortEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ReadOptions_SortEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_AggregateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_AggregateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Meta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Meta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_AllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_AllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_BatchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_BatchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FunctionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_FunctionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FunctionsPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_FunctionsPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FeedData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_FeedData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RealTimeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RealTimeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RealTimeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RealTimeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ProfilesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ProfilesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_EditProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_EditProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SignInRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SignInRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SignUpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SignUpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreateFolderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreateFolderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ListFilesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ListFilesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DeleteFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DeleteFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DownloadFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DownloadFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UploadFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UploadFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FilePayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_FilePayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\022\005proto\"O\n\rCreateRequest\022\020" +
      "\n\010document\030\001 \001(\014\022\021\n\toperation\030\002 \001(\t\022\031\n\004m" +
      "eta\030\003 \001(\0132\013.proto.Meta\"n\n\013ReadRequest\022\014\n" +
      "\004find\030\001 \001(\014\022\021\n\toperation\030\002 \001(\t\022#\n\007option" +
      "s\030\003 \001(\0132\022.proto.ReadOptions\022\031\n\004meta\030\004 \001(" +
      "\0132\013.proto.Meta\"\364\001\n\013ReadOptions\022.\n\006select" +
      "\030\001 \003(\0132\036.proto.ReadOptions.SelectEntry\022*" +
      "\n\004sort\030\002 \003(\0132\034.proto.ReadOptions.SortEnt" +
      "ry\022\014\n\004skip\030\003 \001(\003\022\r\n\005limit\030\004 \001(\003\022\020\n\010disti" +
      "nct\030\005 \001(\t\032-\n\013SelectEntry\022\013\n\003key\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\005:\0028\001\032+\n\tSortEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\005:\0028\001\"[\n\rUpdateRequest\022\014" +
      "\n\004find\030\001 \001(\014\022\021\n\toperation\030\002 \001(\t\022\016\n\006updat" +
      "e\030\003 \001(\014\022\031\n\004meta\030\004 \001(\0132\013.proto.Meta\"K\n\rDe" +
      "leteRequest\022\014\n\004find\030\001 \001(\014\022\021\n\toperation\030\002" +
      " \001(\t\022\031\n\004meta\030\003 \001(\0132\013.proto.Meta\"R\n\020Aggre" +
      "gateRequest\022\020\n\010pipeline\030\001 \001(\014\022\021\n\toperati" +
      "on\030\002 \001(\t\022\031\n\004meta\030\003 \001(\0132\013.proto.Meta\"9\n\010R" +
      "esponse\022\016\n\006status\030\001 \001(\005\022\r\n\005error\030\002 \001(\t\022\016" +
      "\n\006result\030\003 \001(\014\"C\n\004Meta\022\017\n\007project\030\001 \001(\t\022" +
      "\016\n\006dbType\030\002 \001(\t\022\013\n\003col\030\003 \001(\t\022\r\n\005token\030\004 " +
      "\001(\t\"j\n\nAllRequest\022\013\n\003col\030\001 \001(\t\022\020\n\010docume" +
      "nt\030\002 \001(\014\022\021\n\toperation\030\003 \001(\t\022\014\n\004find\030\004 \001(" +
      "\014\022\016\n\006update\030\005 \001(\014\022\014\n\004type\030\006 \001(\t\"R\n\014Batch" +
      "Request\022\'\n\014batchrequest\030\001 \003(\0132\021.proto.Al" +
      "lRequest\022\031\n\004meta\030\002 \001(\0132\013.proto.Meta\"v\n\020F" +
      "unctionsRequest\022\016\n\006params\030\001 \001(\014\022\017\n\007timeo" +
      "ut\030\002 \001(\003\022\017\n\007service\030\003 \001(\t\022\020\n\010function\030\004 " +
      "\001(\t\022\r\n\005token\030\005 \001(\t\022\017\n\007project\030\006 \001(\t\"\234\001\n\020" +
      "FunctionsPayload\022\014\n\004auth\030\001 \001(\014\022\016\n\006params" +
      "\030\002 \001(\014\022\017\n\007service\030\003 \001(\t\022\020\n\010function\030\004 \001(" +
      "\t\022\014\n\004type\030\005 \001(\t\022\n\n\002id\030\006 \001(\t\022\r\n\005error\030\007 \001" +
      "(\t\022\017\n\007project\030\010 \001(\t\022\r\n\005token\030\t \001(\t\"{\n\010Fe" +
      "edData\022\017\n\007queryId\030\001 \001(\t\022\r\n\005docId\030\002 \001(\t\022\014" +
      "\n\004type\030\003 \001(\t\022\r\n\005group\030\004 \001(\t\022\016\n\006dbType\030\005 " +
      "\001(\t\022\017\n\007payload\030\006 \001(\014\022\021\n\ttimeStamp\030\007 \001(\003\"" +
      "y\n\017RealTimeRequest\022\r\n\005token\030\001 \001(\t\022\016\n\006dbT" +
      "ype\030\002 \001(\t\022\017\n\007project\030\003 \001(\t\022\r\n\005group\030\004 \001(" +
      "\t\022\014\n\004type\030\005 \001(\t\022\n\n\002id\030\006 \001(\t\022\r\n\005where\030\007 \001" +
      "(\014\"l\n\020RealTimeResponse\022\r\n\005group\030\001 \001(\t\022\n\n" +
      "\002id\030\002 \001(\t\022\013\n\003ack\030\003 \001(\010\022\r\n\005error\030\004 \001(\t\022!\n" +
      "\010feedData\030\005 \003(\0132\017.proto.FeedData\"7\n\016Prof" +
      "ileRequest\022\n\n\002id\030\001 \001(\t\022\031\n\004meta\030\002 \001(\0132\013.p" +
      "roto.Meta\",\n\017ProfilesRequest\022\031\n\004meta\030\001 \001" +
      "(\0132\013.proto.Meta\"j\n\022EditProfileRequest\022\n\n" +
      "\002id\030\001 \001(\t\022\r\n\005email\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\020" +
      "\n\010password\030\004 \001(\t\022\031\n\004meta\030\005 \001(\0132\013.proto.M" +
      "eta\"K\n\rSignInRequest\022\r\n\005email\030\001 \001(\t\022\020\n\010p" +
      "assword\030\002 \001(\t\022\031\n\004meta\030\003 \001(\0132\013.proto.Meta" +
      "\"g\n\rSignUpRequest\022\r\n\005email\030\001 \001(\t\022\014\n\004name" +
      "\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\014\n\004role\030\004 \001(\t\022\031" +
      "\n\004meta\030\005 \001(\0132\013.proto.Meta\"L\n\023CreateFolde" +
      "rRequest\022\014\n\004path\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\031\n\004" +
      "meta\030\003 \001(\0132\013.proto.Meta\";\n\020ListFilesRequ" +
      "est\022\014\n\004path\030\001 \001(\t\022\031\n\004meta\030\002 \001(\0132\013.proto." +
      "Meta\"<\n\021DeleteFileRequest\022\014\n\004path\030\001 \001(\t\022" +
      "\031\n\004meta\030\002 \001(\0132\013.proto.Meta\">\n\023DownloadFi" +
      "leRequest\022\014\n\004path\030\001 \001(\t\022\031\n\004meta\030\002 \001(\0132\013." +
      "proto.Meta\"[\n\021UploadFileRequest\022\014\n\004path\030" +
      "\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\017\n\007payload\030\003 \001(\014\022\031\n\004" +
      "meta\030\004 \001(\0132\013.proto.Meta\"=\n\013FilePayload\022\016" +
      "\n\006status\030\001 \001(\005\022\r\n\005error\030\002 \001(\t\022\017\n\007payload" +
      "\030\003 \001(\0142\273\010\n\nSpaceCloud\0221\n\006Create\022\024.proto." +
      "CreateRequest\032\017.proto.Response\"\000\022-\n\004Read" +
      "\022\022.proto.ReadRequest\032\017.proto.Response\"\000\022" +
      "1\n\006Update\022\024.proto.UpdateRequest\032\017.proto." +
      "Response\"\000\0221\n\006Delete\022\024.proto.DeleteReque" +
      "st\032\017.proto.Response\"\000\0227\n\tAggregate\022\027.pro" +
      "to.AggregateRequest\032\017.proto.Response\"\000\022/" +
      "\n\005Batch\022\023.proto.BatchRequest\032\017.proto.Res" +
      "ponse\"\000\0222\n\004Call\022\027.proto.FunctionsRequest" +
      "\032\017.proto.Response\"\000\022A\n\010RealTime\022\026.proto." +
      "RealTimeRequest\032\027.proto.RealTimeResponse" +
      "\"\000(\0010\001\022A\n\007Service\022\027.proto.FunctionsPaylo" +
      "ad\032\027.proto.FunctionsPayload\"\000(\0010\001\0223\n\007Pro" +
      "file\022\025.proto.ProfileRequest\032\017.proto.Resp" +
      "onse\"\000\0225\n\010Profiles\022\026.proto.ProfilesReque" +
      "st\032\017.proto.Response\"\000\022;\n\013EditProfile\022\031.p" +
      "roto.EditProfileRequest\032\017.proto.Response" +
      "\"\000\0221\n\006SignIn\022\024.proto.SignInRequest\032\017.pro" +
      "to.Response\"\000\0221\n\006SignUp\022\024.proto.SignUpRe" +
      "quest\032\017.proto.Response\"\000\022=\n\014CreateFolder" +
      "\022\032.proto.CreateFolderRequest\032\017.proto.Res" +
      "ponse\"\000\0227\n\tListFiles\022\027.proto.ListFilesRe" +
      "quest\032\017.proto.Response\"\000\0229\n\nDeleteFile\022\030" +
      ".proto.DeleteFileRequest\032\017.proto.Respons" +
      "e\"\000\022;\n\nUploadFile\022\030.proto.UploadFileRequ" +
      "est\032\017.proto.Response\"\000(\001\022B\n\014DownloadFile" +
      "\022\032.proto.DownloadFileRequest\032\022.proto.Fil" +
      "ePayload\"\0000\001B4\n\037com.spaceuptech.space_ap" +
      "i.protoB\017SpaceCloudProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_CreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreateRequest_descriptor,
        new java.lang.String[] { "Document", "Operation", "Meta", });
    internal_static_proto_ReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ReadRequest_descriptor,
        new java.lang.String[] { "Find", "Operation", "Options", "Meta", });
    internal_static_proto_ReadOptions_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_ReadOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ReadOptions_descriptor,
        new java.lang.String[] { "Select", "Sort", "Skip", "Limit", "Distinct", });
    internal_static_proto_ReadOptions_SelectEntry_descriptor =
      internal_static_proto_ReadOptions_descriptor.getNestedTypes().get(0);
    internal_static_proto_ReadOptions_SelectEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ReadOptions_SelectEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_proto_ReadOptions_SortEntry_descriptor =
      internal_static_proto_ReadOptions_descriptor.getNestedTypes().get(1);
    internal_static_proto_ReadOptions_SortEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ReadOptions_SortEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_proto_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UpdateRequest_descriptor,
        new java.lang.String[] { "Find", "Operation", "Update", "Meta", });
    internal_static_proto_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DeleteRequest_descriptor,
        new java.lang.String[] { "Find", "Operation", "Meta", });
    internal_static_proto_AggregateRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_AggregateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_AggregateRequest_descriptor,
        new java.lang.String[] { "Pipeline", "Operation", "Meta", });
    internal_static_proto_Response_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_proto_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Response_descriptor,
        new java.lang.String[] { "Status", "Error", "Result", });
    internal_static_proto_Meta_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_proto_Meta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Meta_descriptor,
        new java.lang.String[] { "Project", "DbType", "Col", "Token", });
    internal_static_proto_AllRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_proto_AllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_AllRequest_descriptor,
        new java.lang.String[] { "Col", "Document", "Operation", "Find", "Update", "Type", });
    internal_static_proto_BatchRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_proto_BatchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_BatchRequest_descriptor,
        new java.lang.String[] { "Batchrequest", "Meta", });
    internal_static_proto_FunctionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_proto_FunctionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_FunctionsRequest_descriptor,
        new java.lang.String[] { "Params", "Timeout", "Service", "Function", "Token", "Project", });
    internal_static_proto_FunctionsPayload_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_proto_FunctionsPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_FunctionsPayload_descriptor,
        new java.lang.String[] { "Auth", "Params", "Service", "Function", "Type", "Id", "Error", "Project", "Token", });
    internal_static_proto_FeedData_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_proto_FeedData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_FeedData_descriptor,
        new java.lang.String[] { "QueryId", "DocId", "Type", "Group", "DbType", "Payload", "TimeStamp", });
    internal_static_proto_RealTimeRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_proto_RealTimeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RealTimeRequest_descriptor,
        new java.lang.String[] { "Token", "DbType", "Project", "Group", "Type", "Id", "Where", });
    internal_static_proto_RealTimeResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_proto_RealTimeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RealTimeResponse_descriptor,
        new java.lang.String[] { "Group", "Id", "Ack", "Error", "FeedData", });
    internal_static_proto_ProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_proto_ProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ProfileRequest_descriptor,
        new java.lang.String[] { "Id", "Meta", });
    internal_static_proto_ProfilesRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_proto_ProfilesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ProfilesRequest_descriptor,
        new java.lang.String[] { "Meta", });
    internal_static_proto_EditProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_proto_EditProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_EditProfileRequest_descriptor,
        new java.lang.String[] { "Id", "Email", "Name", "Password", "Meta", });
    internal_static_proto_SignInRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_proto_SignInRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SignInRequest_descriptor,
        new java.lang.String[] { "Email", "Password", "Meta", });
    internal_static_proto_SignUpRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_proto_SignUpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SignUpRequest_descriptor,
        new java.lang.String[] { "Email", "Name", "Password", "Role", "Meta", });
    internal_static_proto_CreateFolderRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_proto_CreateFolderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreateFolderRequest_descriptor,
        new java.lang.String[] { "Path", "Name", "Meta", });
    internal_static_proto_ListFilesRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_proto_ListFilesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ListFilesRequest_descriptor,
        new java.lang.String[] { "Path", "Meta", });
    internal_static_proto_DeleteFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_proto_DeleteFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DeleteFileRequest_descriptor,
        new java.lang.String[] { "Path", "Meta", });
    internal_static_proto_DownloadFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_proto_DownloadFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DownloadFileRequest_descriptor,
        new java.lang.String[] { "Path", "Meta", });
    internal_static_proto_UploadFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_proto_UploadFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UploadFileRequest_descriptor,
        new java.lang.String[] { "Path", "Name", "Payload", "Meta", });
    internal_static_proto_FilePayload_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_proto_FilePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_FilePayload_descriptor,
        new java.lang.String[] { "Status", "Error", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
