// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.api.core.proto;

/**
 * Protobuf type {@code proto.BatchRequest}
 */
public  final class BatchRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.BatchRequest)
    BatchRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BatchRequest.newBuilder() to construct.
  private BatchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BatchRequest() {
    batchrequest_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BatchRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              batchrequest_ = new java.util.ArrayList<com.spaceuptech.api.core.proto.AllRequest>();
              mutable_bitField0_ |= 0x00000001;
            }
            batchrequest_.add(
                input.readMessage(com.spaceuptech.api.core.proto.AllRequest.parser(), extensionRegistry));
            break;
          }
          case 18: {
            com.spaceuptech.api.core.proto.Meta.Builder subBuilder = null;
            if (meta_ != null) {
              subBuilder = meta_.toBuilder();
            }
            meta_ = input.readMessage(com.spaceuptech.api.core.proto.Meta.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(meta_);
              meta_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        batchrequest_ = java.util.Collections.unmodifiableList(batchrequest_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.spaceuptech.api.core.proto.SpaceCloudProto.internal_static_proto_BatchRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.spaceuptech.api.core.proto.SpaceCloudProto.internal_static_proto_BatchRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.spaceuptech.api.core.proto.BatchRequest.class, com.spaceuptech.api.core.proto.BatchRequest.Builder.class);
  }

  private int bitField0_;
  public static final int BATCHREQUEST_FIELD_NUMBER = 1;
  private java.util.List<com.spaceuptech.api.core.proto.AllRequest> batchrequest_;
  /**
   * <code>repeated .proto.AllRequest batchrequest = 1;</code>
   */
  public java.util.List<com.spaceuptech.api.core.proto.AllRequest> getBatchrequestList() {
    return batchrequest_;
  }
  /**
   * <code>repeated .proto.AllRequest batchrequest = 1;</code>
   */
  public java.util.List<? extends com.spaceuptech.api.core.proto.AllRequestOrBuilder> 
      getBatchrequestOrBuilderList() {
    return batchrequest_;
  }
  /**
   * <code>repeated .proto.AllRequest batchrequest = 1;</code>
   */
  public int getBatchrequestCount() {
    return batchrequest_.size();
  }
  /**
   * <code>repeated .proto.AllRequest batchrequest = 1;</code>
   */
  public com.spaceuptech.api.core.proto.AllRequest getBatchrequest(int index) {
    return batchrequest_.get(index);
  }
  /**
   * <code>repeated .proto.AllRequest batchrequest = 1;</code>
   */
  public com.spaceuptech.api.core.proto.AllRequestOrBuilder getBatchrequestOrBuilder(
      int index) {
    return batchrequest_.get(index);
  }

  public static final int META_FIELD_NUMBER = 2;
  private com.spaceuptech.api.core.proto.Meta meta_;
  /**
   * <code>.proto.Meta meta = 2;</code>
   */
  public boolean hasMeta() {
    return meta_ != null;
  }
  /**
   * <code>.proto.Meta meta = 2;</code>
   */
  public com.spaceuptech.api.core.proto.Meta getMeta() {
    return meta_ == null ? com.spaceuptech.api.core.proto.Meta.getDefaultInstance() : meta_;
  }
  /**
   * <code>.proto.Meta meta = 2;</code>
   */
  public com.spaceuptech.api.core.proto.MetaOrBuilder getMetaOrBuilder() {
    return getMeta();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < batchrequest_.size(); i++) {
      output.writeMessage(1, batchrequest_.get(i));
    }
    if (meta_ != null) {
      output.writeMessage(2, getMeta());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < batchrequest_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, batchrequest_.get(i));
    }
    if (meta_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMeta());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.spaceuptech.api.core.proto.BatchRequest)) {
      return super.equals(obj);
    }
    com.spaceuptech.api.core.proto.BatchRequest other = (com.spaceuptech.api.core.proto.BatchRequest) obj;

    boolean result = true;
    result = result && getBatchrequestList()
        .equals(other.getBatchrequestList());
    result = result && (hasMeta() == other.hasMeta());
    if (hasMeta()) {
      result = result && getMeta()
          .equals(other.getMeta());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBatchrequestCount() > 0) {
      hash = (37 * hash) + BATCHREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getBatchrequestList().hashCode();
    }
    if (hasMeta()) {
      hash = (37 * hash) + META_FIELD_NUMBER;
      hash = (53 * hash) + getMeta().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.spaceuptech.api.core.proto.BatchRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spaceuptech.api.core.proto.BatchRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spaceuptech.api.core.proto.BatchRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spaceuptech.api.core.proto.BatchRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spaceuptech.api.core.proto.BatchRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spaceuptech.api.core.proto.BatchRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spaceuptech.api.core.proto.BatchRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.spaceuptech.api.core.proto.BatchRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.spaceuptech.api.core.proto.BatchRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.spaceuptech.api.core.proto.BatchRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.spaceuptech.api.core.proto.BatchRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.spaceuptech.api.core.proto.BatchRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.spaceuptech.api.core.proto.BatchRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.BatchRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.BatchRequest)
      com.spaceuptech.api.core.proto.BatchRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spaceuptech.api.core.proto.SpaceCloudProto.internal_static_proto_BatchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spaceuptech.api.core.proto.SpaceCloudProto.internal_static_proto_BatchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.spaceuptech.api.core.proto.BatchRequest.class, com.spaceuptech.api.core.proto.BatchRequest.Builder.class);
    }

    // Construct using com.spaceuptech.api.core.proto.BatchRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBatchrequestFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (batchrequestBuilder_ == null) {
        batchrequest_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        batchrequestBuilder_.clear();
      }
      if (metaBuilder_ == null) {
        meta_ = null;
      } else {
        meta_ = null;
        metaBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.spaceuptech.api.core.proto.SpaceCloudProto.internal_static_proto_BatchRequest_descriptor;
    }

    @java.lang.Override
    public com.spaceuptech.api.core.proto.BatchRequest getDefaultInstanceForType() {
      return com.spaceuptech.api.core.proto.BatchRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.spaceuptech.api.core.proto.BatchRequest build() {
      com.spaceuptech.api.core.proto.BatchRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.spaceuptech.api.core.proto.BatchRequest buildPartial() {
      com.spaceuptech.api.core.proto.BatchRequest result = new com.spaceuptech.api.core.proto.BatchRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (batchrequestBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          batchrequest_ = java.util.Collections.unmodifiableList(batchrequest_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.batchrequest_ = batchrequest_;
      } else {
        result.batchrequest_ = batchrequestBuilder_.build();
      }
      if (metaBuilder_ == null) {
        result.meta_ = meta_;
      } else {
        result.meta_ = metaBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.spaceuptech.api.core.proto.BatchRequest) {
        return mergeFrom((com.spaceuptech.api.core.proto.BatchRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.spaceuptech.api.core.proto.BatchRequest other) {
      if (other == com.spaceuptech.api.core.proto.BatchRequest.getDefaultInstance()) return this;
      if (batchrequestBuilder_ == null) {
        if (!other.batchrequest_.isEmpty()) {
          if (batchrequest_.isEmpty()) {
            batchrequest_ = other.batchrequest_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBatchrequestIsMutable();
            batchrequest_.addAll(other.batchrequest_);
          }
          onChanged();
        }
      } else {
        if (!other.batchrequest_.isEmpty()) {
          if (batchrequestBuilder_.isEmpty()) {
            batchrequestBuilder_.dispose();
            batchrequestBuilder_ = null;
            batchrequest_ = other.batchrequest_;
            bitField0_ = (bitField0_ & ~0x00000001);
            batchrequestBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBatchrequestFieldBuilder() : null;
          } else {
            batchrequestBuilder_.addAllMessages(other.batchrequest_);
          }
        }
      }
      if (other.hasMeta()) {
        mergeMeta(other.getMeta());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.spaceuptech.api.core.proto.BatchRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.spaceuptech.api.core.proto.BatchRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.spaceuptech.api.core.proto.AllRequest> batchrequest_ =
      java.util.Collections.emptyList();
    private void ensureBatchrequestIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        batchrequest_ = new java.util.ArrayList<com.spaceuptech.api.core.proto.AllRequest>(batchrequest_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.spaceuptech.api.core.proto.AllRequest, com.spaceuptech.api.core.proto.AllRequest.Builder, com.spaceuptech.api.core.proto.AllRequestOrBuilder> batchrequestBuilder_;

    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public java.util.List<com.spaceuptech.api.core.proto.AllRequest> getBatchrequestList() {
      if (batchrequestBuilder_ == null) {
        return java.util.Collections.unmodifiableList(batchrequest_);
      } else {
        return batchrequestBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public int getBatchrequestCount() {
      if (batchrequestBuilder_ == null) {
        return batchrequest_.size();
      } else {
        return batchrequestBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public com.spaceuptech.api.core.proto.AllRequest getBatchrequest(int index) {
      if (batchrequestBuilder_ == null) {
        return batchrequest_.get(index);
      } else {
        return batchrequestBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public Builder setBatchrequest(
        int index, com.spaceuptech.api.core.proto.AllRequest value) {
      if (batchrequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBatchrequestIsMutable();
        batchrequest_.set(index, value);
        onChanged();
      } else {
        batchrequestBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public Builder setBatchrequest(
        int index, com.spaceuptech.api.core.proto.AllRequest.Builder builderForValue) {
      if (batchrequestBuilder_ == null) {
        ensureBatchrequestIsMutable();
        batchrequest_.set(index, builderForValue.build());
        onChanged();
      } else {
        batchrequestBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public Builder addBatchrequest(com.spaceuptech.api.core.proto.AllRequest value) {
      if (batchrequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBatchrequestIsMutable();
        batchrequest_.add(value);
        onChanged();
      } else {
        batchrequestBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public Builder addBatchrequest(
        int index, com.spaceuptech.api.core.proto.AllRequest value) {
      if (batchrequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBatchrequestIsMutable();
        batchrequest_.add(index, value);
        onChanged();
      } else {
        batchrequestBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public Builder addBatchrequest(
        com.spaceuptech.api.core.proto.AllRequest.Builder builderForValue) {
      if (batchrequestBuilder_ == null) {
        ensureBatchrequestIsMutable();
        batchrequest_.add(builderForValue.build());
        onChanged();
      } else {
        batchrequestBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public Builder addBatchrequest(
        int index, com.spaceuptech.api.core.proto.AllRequest.Builder builderForValue) {
      if (batchrequestBuilder_ == null) {
        ensureBatchrequestIsMutable();
        batchrequest_.add(index, builderForValue.build());
        onChanged();
      } else {
        batchrequestBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public Builder addAllBatchrequest(
        java.lang.Iterable<? extends com.spaceuptech.api.core.proto.AllRequest> values) {
      if (batchrequestBuilder_ == null) {
        ensureBatchrequestIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, batchrequest_);
        onChanged();
      } else {
        batchrequestBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public Builder clearBatchrequest() {
      if (batchrequestBuilder_ == null) {
        batchrequest_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        batchrequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public Builder removeBatchrequest(int index) {
      if (batchrequestBuilder_ == null) {
        ensureBatchrequestIsMutable();
        batchrequest_.remove(index);
        onChanged();
      } else {
        batchrequestBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public com.spaceuptech.api.core.proto.AllRequest.Builder getBatchrequestBuilder(
        int index) {
      return getBatchrequestFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public com.spaceuptech.api.core.proto.AllRequestOrBuilder getBatchrequestOrBuilder(
        int index) {
      if (batchrequestBuilder_ == null) {
        return batchrequest_.get(index);  } else {
        return batchrequestBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public java.util.List<? extends com.spaceuptech.api.core.proto.AllRequestOrBuilder> 
         getBatchrequestOrBuilderList() {
      if (batchrequestBuilder_ != null) {
        return batchrequestBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(batchrequest_);
      }
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public com.spaceuptech.api.core.proto.AllRequest.Builder addBatchrequestBuilder() {
      return getBatchrequestFieldBuilder().addBuilder(
          com.spaceuptech.api.core.proto.AllRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public com.spaceuptech.api.core.proto.AllRequest.Builder addBatchrequestBuilder(
        int index) {
      return getBatchrequestFieldBuilder().addBuilder(
          index, com.spaceuptech.api.core.proto.AllRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.AllRequest batchrequest = 1;</code>
     */
    public java.util.List<com.spaceuptech.api.core.proto.AllRequest.Builder> 
         getBatchrequestBuilderList() {
      return getBatchrequestFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.spaceuptech.api.core.proto.AllRequest, com.spaceuptech.api.core.proto.AllRequest.Builder, com.spaceuptech.api.core.proto.AllRequestOrBuilder> 
        getBatchrequestFieldBuilder() {
      if (batchrequestBuilder_ == null) {
        batchrequestBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.spaceuptech.api.core.proto.AllRequest, com.spaceuptech.api.core.proto.AllRequest.Builder, com.spaceuptech.api.core.proto.AllRequestOrBuilder>(
                batchrequest_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        batchrequest_ = null;
      }
      return batchrequestBuilder_;
    }

    private com.spaceuptech.api.core.proto.Meta meta_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.spaceuptech.api.core.proto.Meta, com.spaceuptech.api.core.proto.Meta.Builder, com.spaceuptech.api.core.proto.MetaOrBuilder> metaBuilder_;
    /**
     * <code>.proto.Meta meta = 2;</code>
     */
    public boolean hasMeta() {
      return metaBuilder_ != null || meta_ != null;
    }
    /**
     * <code>.proto.Meta meta = 2;</code>
     */
    public com.spaceuptech.api.core.proto.Meta getMeta() {
      if (metaBuilder_ == null) {
        return meta_ == null ? com.spaceuptech.api.core.proto.Meta.getDefaultInstance() : meta_;
      } else {
        return metaBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.Meta meta = 2;</code>
     */
    public Builder setMeta(com.spaceuptech.api.core.proto.Meta value) {
      if (metaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        meta_ = value;
        onChanged();
      } else {
        metaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.Meta meta = 2;</code>
     */
    public Builder setMeta(
        com.spaceuptech.api.core.proto.Meta.Builder builderForValue) {
      if (metaBuilder_ == null) {
        meta_ = builderForValue.build();
        onChanged();
      } else {
        metaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.Meta meta = 2;</code>
     */
    public Builder mergeMeta(com.spaceuptech.api.core.proto.Meta value) {
      if (metaBuilder_ == null) {
        if (meta_ != null) {
          meta_ =
            com.spaceuptech.api.core.proto.Meta.newBuilder(meta_).mergeFrom(value).buildPartial();
        } else {
          meta_ = value;
        }
        onChanged();
      } else {
        metaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.Meta meta = 2;</code>
     */
    public Builder clearMeta() {
      if (metaBuilder_ == null) {
        meta_ = null;
        onChanged();
      } else {
        meta_ = null;
        metaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.Meta meta = 2;</code>
     */
    public com.spaceuptech.api.core.proto.Meta.Builder getMetaBuilder() {
      
      onChanged();
      return getMetaFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.Meta meta = 2;</code>
     */
    public com.spaceuptech.api.core.proto.MetaOrBuilder getMetaOrBuilder() {
      if (metaBuilder_ != null) {
        return metaBuilder_.getMessageOrBuilder();
      } else {
        return meta_ == null ?
            com.spaceuptech.api.core.proto.Meta.getDefaultInstance() : meta_;
      }
    }
    /**
     * <code>.proto.Meta meta = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.spaceuptech.api.core.proto.Meta, com.spaceuptech.api.core.proto.Meta.Builder, com.spaceuptech.api.core.proto.MetaOrBuilder> 
        getMetaFieldBuilder() {
      if (metaBuilder_ == null) {
        metaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.spaceuptech.api.core.proto.Meta, com.spaceuptech.api.core.proto.Meta.Builder, com.spaceuptech.api.core.proto.MetaOrBuilder>(
                getMeta(),
                getParentForChildren(),
                isClean());
        meta_ = null;
      }
      return metaBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.BatchRequest)
  }

  // @@protoc_insertion_point(class_scope:proto.BatchRequest)
  private static final com.spaceuptech.api.core.proto.BatchRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.spaceuptech.api.core.proto.BatchRequest();
  }

  public static com.spaceuptech.api.core.proto.BatchRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchRequest>
      PARSER = new com.google.protobuf.AbstractParser<BatchRequest>() {
    @java.lang.Override
    public BatchRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BatchRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BatchRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatchRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.spaceuptech.api.core.proto.BatchRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

