// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.api.core.proto;

public interface FaaSRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.FaaSRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes params = 1;</code>
   */
  com.google.protobuf.ByteString getParams();

  /**
   * <code>int64 timeout = 2;</code>
   */
  long getTimeout();

  /**
   * <code>string engine = 3;</code>
   */
  java.lang.String getEngine();
  /**
   * <code>string engine = 3;</code>
   */
  com.google.protobuf.ByteString
      getEngineBytes();

  /**
   * <code>string function = 4;</code>
   */
  java.lang.String getFunction();
  /**
   * <code>string function = 4;</code>
   */
  com.google.protobuf.ByteString
      getFunctionBytes();

  /**
   * <code>string token = 5;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 5;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
