// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.api.core.proto;

/**
 * Protobuf type {@code proto.FaaSRequest}
 */
public  final class FaaSRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.FaaSRequest)
    FaaSRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FaaSRequest.newBuilder() to construct.
  private FaaSRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FaaSRequest() {
    params_ = com.google.protobuf.ByteString.EMPTY;
    timeout_ = 0L;
    engine_ = "";
    function_ = "";
    token_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FaaSRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            params_ = input.readBytes();
            break;
          }
          case 16: {

            timeout_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            engine_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            function_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            token_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.spaceuptech.api.core.proto.SpaceCloudProto.internal_static_proto_FaaSRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.spaceuptech.api.core.proto.SpaceCloudProto.internal_static_proto_FaaSRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.spaceuptech.api.core.proto.FaaSRequest.class, com.spaceuptech.api.core.proto.FaaSRequest.Builder.class);
  }

  public static final int PARAMS_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString params_;
  /**
   * <code>bytes params = 1;</code>
   */
  public com.google.protobuf.ByteString getParams() {
    return params_;
  }

  public static final int TIMEOUT_FIELD_NUMBER = 2;
  private long timeout_;
  /**
   * <code>int64 timeout = 2;</code>
   */
  public long getTimeout() {
    return timeout_;
  }

  public static final int ENGINE_FIELD_NUMBER = 3;
  private volatile java.lang.Object engine_;
  /**
   * <code>string engine = 3;</code>
   */
  public java.lang.String getEngine() {
    java.lang.Object ref = engine_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      engine_ = s;
      return s;
    }
  }
  /**
   * <code>string engine = 3;</code>
   */
  public com.google.protobuf.ByteString
      getEngineBytes() {
    java.lang.Object ref = engine_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      engine_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FUNCTION_FIELD_NUMBER = 4;
  private volatile java.lang.Object function_;
  /**
   * <code>string function = 4;</code>
   */
  public java.lang.String getFunction() {
    java.lang.Object ref = function_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      function_ = s;
      return s;
    }
  }
  /**
   * <code>string function = 4;</code>
   */
  public com.google.protobuf.ByteString
      getFunctionBytes() {
    java.lang.Object ref = function_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      function_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKEN_FIELD_NUMBER = 5;
  private volatile java.lang.Object token_;
  /**
   * <code>string token = 5;</code>
   */
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <code>string token = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!params_.isEmpty()) {
      output.writeBytes(1, params_);
    }
    if (timeout_ != 0L) {
      output.writeInt64(2, timeout_);
    }
    if (!getEngineBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, engine_);
    }
    if (!getFunctionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, function_);
    }
    if (!getTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, token_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!params_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, params_);
    }
    if (timeout_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timeout_);
    }
    if (!getEngineBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, engine_);
    }
    if (!getFunctionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, function_);
    }
    if (!getTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, token_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.spaceuptech.api.core.proto.FaaSRequest)) {
      return super.equals(obj);
    }
    com.spaceuptech.api.core.proto.FaaSRequest other = (com.spaceuptech.api.core.proto.FaaSRequest) obj;

    boolean result = true;
    result = result && getParams()
        .equals(other.getParams());
    result = result && (getTimeout()
        == other.getTimeout());
    result = result && getEngine()
        .equals(other.getEngine());
    result = result && getFunction()
        .equals(other.getFunction());
    result = result && getToken()
        .equals(other.getToken());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PARAMS_FIELD_NUMBER;
    hash = (53 * hash) + getParams().hashCode();
    hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeout());
    hash = (37 * hash) + ENGINE_FIELD_NUMBER;
    hash = (53 * hash) + getEngine().hashCode();
    hash = (37 * hash) + FUNCTION_FIELD_NUMBER;
    hash = (53 * hash) + getFunction().hashCode();
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.spaceuptech.api.core.proto.FaaSRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spaceuptech.api.core.proto.FaaSRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spaceuptech.api.core.proto.FaaSRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spaceuptech.api.core.proto.FaaSRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spaceuptech.api.core.proto.FaaSRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spaceuptech.api.core.proto.FaaSRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spaceuptech.api.core.proto.FaaSRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.spaceuptech.api.core.proto.FaaSRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.spaceuptech.api.core.proto.FaaSRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.spaceuptech.api.core.proto.FaaSRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.spaceuptech.api.core.proto.FaaSRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.spaceuptech.api.core.proto.FaaSRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.spaceuptech.api.core.proto.FaaSRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.FaaSRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.FaaSRequest)
      com.spaceuptech.api.core.proto.FaaSRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spaceuptech.api.core.proto.SpaceCloudProto.internal_static_proto_FaaSRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spaceuptech.api.core.proto.SpaceCloudProto.internal_static_proto_FaaSRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.spaceuptech.api.core.proto.FaaSRequest.class, com.spaceuptech.api.core.proto.FaaSRequest.Builder.class);
    }

    // Construct using com.spaceuptech.api.core.proto.FaaSRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      params_ = com.google.protobuf.ByteString.EMPTY;

      timeout_ = 0L;

      engine_ = "";

      function_ = "";

      token_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.spaceuptech.api.core.proto.SpaceCloudProto.internal_static_proto_FaaSRequest_descriptor;
    }

    @java.lang.Override
    public com.spaceuptech.api.core.proto.FaaSRequest getDefaultInstanceForType() {
      return com.spaceuptech.api.core.proto.FaaSRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.spaceuptech.api.core.proto.FaaSRequest build() {
      com.spaceuptech.api.core.proto.FaaSRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.spaceuptech.api.core.proto.FaaSRequest buildPartial() {
      com.spaceuptech.api.core.proto.FaaSRequest result = new com.spaceuptech.api.core.proto.FaaSRequest(this);
      result.params_ = params_;
      result.timeout_ = timeout_;
      result.engine_ = engine_;
      result.function_ = function_;
      result.token_ = token_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.spaceuptech.api.core.proto.FaaSRequest) {
        return mergeFrom((com.spaceuptech.api.core.proto.FaaSRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.spaceuptech.api.core.proto.FaaSRequest other) {
      if (other == com.spaceuptech.api.core.proto.FaaSRequest.getDefaultInstance()) return this;
      if (other.getParams() != com.google.protobuf.ByteString.EMPTY) {
        setParams(other.getParams());
      }
      if (other.getTimeout() != 0L) {
        setTimeout(other.getTimeout());
      }
      if (!other.getEngine().isEmpty()) {
        engine_ = other.engine_;
        onChanged();
      }
      if (!other.getFunction().isEmpty()) {
        function_ = other.function_;
        onChanged();
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.spaceuptech.api.core.proto.FaaSRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.spaceuptech.api.core.proto.FaaSRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString params_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes params = 1;</code>
     */
    public com.google.protobuf.ByteString getParams() {
      return params_;
    }
    /**
     * <code>bytes params = 1;</code>
     */
    public Builder setParams(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      params_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes params = 1;</code>
     */
    public Builder clearParams() {
      
      params_ = getDefaultInstance().getParams();
      onChanged();
      return this;
    }

    private long timeout_ ;
    /**
     * <code>int64 timeout = 2;</code>
     */
    public long getTimeout() {
      return timeout_;
    }
    /**
     * <code>int64 timeout = 2;</code>
     */
    public Builder setTimeout(long value) {
      
      timeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timeout = 2;</code>
     */
    public Builder clearTimeout() {
      
      timeout_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object engine_ = "";
    /**
     * <code>string engine = 3;</code>
     */
    public java.lang.String getEngine() {
      java.lang.Object ref = engine_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        engine_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string engine = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEngineBytes() {
      java.lang.Object ref = engine_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        engine_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string engine = 3;</code>
     */
    public Builder setEngine(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      engine_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string engine = 3;</code>
     */
    public Builder clearEngine() {
      
      engine_ = getDefaultInstance().getEngine();
      onChanged();
      return this;
    }
    /**
     * <code>string engine = 3;</code>
     */
    public Builder setEngineBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      engine_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object function_ = "";
    /**
     * <code>string function = 4;</code>
     */
    public java.lang.String getFunction() {
      java.lang.Object ref = function_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        function_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string function = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFunctionBytes() {
      java.lang.Object ref = function_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        function_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string function = 4;</code>
     */
    public Builder setFunction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      function_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string function = 4;</code>
     */
    public Builder clearFunction() {
      
      function_ = getDefaultInstance().getFunction();
      onChanged();
      return this;
    }
    /**
     * <code>string function = 4;</code>
     */
    public Builder setFunctionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      function_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object token_ = "";
    /**
     * <code>string token = 5;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string token = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string token = 5;</code>
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string token = 5;</code>
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }
    /**
     * <code>string token = 5;</code>
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      token_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.FaaSRequest)
  }

  // @@protoc_insertion_point(class_scope:proto.FaaSRequest)
  private static final com.spaceuptech.api.core.proto.FaaSRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.spaceuptech.api.core.proto.FaaSRequest();
  }

  public static com.spaceuptech.api.core.proto.FaaSRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FaaSRequest>
      PARSER = new com.google.protobuf.AbstractParser<FaaSRequest>() {
    @java.lang.Override
    public FaaSRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FaaSRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FaaSRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FaaSRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.spaceuptech.api.core.proto.FaaSRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

