// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.api.core.proto;

public interface ReadOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ReadOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, int32&gt; select = 1;</code>
   */
  int getSelectCount();
  /**
   * <code>map&lt;string, int32&gt; select = 1;</code>
   */
  boolean containsSelect(
      java.lang.String key);
  /**
   * Use {@link #getSelectMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Integer>
  getSelect();
  /**
   * <code>map&lt;string, int32&gt; select = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.Integer>
  getSelectMap();
  /**
   * <code>map&lt;string, int32&gt; select = 1;</code>
   */

  int getSelectOrDefault(
      java.lang.String key,
      int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; select = 1;</code>
   */

  int getSelectOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, int32&gt; sort = 2;</code>
   */
  int getSortCount();
  /**
   * <code>map&lt;string, int32&gt; sort = 2;</code>
   */
  boolean containsSort(
      java.lang.String key);
  /**
   * Use {@link #getSortMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Integer>
  getSort();
  /**
   * <code>map&lt;string, int32&gt; sort = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.Integer>
  getSortMap();
  /**
   * <code>map&lt;string, int32&gt; sort = 2;</code>
   */

  int getSortOrDefault(
      java.lang.String key,
      int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; sort = 2;</code>
   */

  int getSortOrThrow(
      java.lang.String key);

  /**
   * <code>int64 skip = 3;</code>
   */
  long getSkip();

  /**
   * <code>int64 limit = 4;</code>
   */
  long getLimit();

  /**
   * <code>string distinct = 5;</code>
   */
  java.lang.String getDistinct();
  /**
   * <code>string distinct = 5;</code>
   */
  com.google.protobuf.ByteString
      getDistinctBytes();
}
