// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.spaceuptech.api.core.proto;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes find = 1;</code>
   */
  com.google.protobuf.ByteString getFind();

  /**
   * <code>string operation = 2;</code>
   */
  java.lang.String getOperation();
  /**
   * <code>string operation = 2;</code>
   */
  com.google.protobuf.ByteString
      getOperationBytes();

  /**
   * <code>bytes update = 3;</code>
   */
  com.google.protobuf.ByteString getUpdate();

  /**
   * <code>.proto.Meta meta = 4;</code>
   */
  boolean hasMeta();
  /**
   * <code>.proto.Meta meta = 4;</code>
   */
  com.spaceuptech.api.core.proto.Meta getMeta();
  /**
   * <code>.proto.Meta meta = 4;</code>
   */
  com.spaceuptech.api.core.proto.MetaOrBuilder getMetaOrBuilder();
}
